### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by eclipsek20** [RuiSiang/monero-merchant#39]
Can you please give instructions on how to use it?

**Comment by RuiSiang** [comment]
Ah, lol, this is sorta an abandoned project from long ago. Didn't have time to finish it. I'll see if I can continue on this in the next few months

**Comment by eclipsek20** [comment]
Out of all the projects I looked at this project seemed most suited for me, if you can continue, I would gladly appreciate it.

**Comment by RuiSiang** [comment]
Suited for what? lol
I'll see what I can do, but it's possible that you'll have to do your own implementation if I don't have time
