### ISSUE TITLE
Validate with regex

### ISSUE THREAD

**Issue by CryptoGrampy** [RuiSiang/monero-merchant#58]
https://github.com/RuiSiang/monero-merchant/blob/9b4cee6445e7b7d76ee008ea30244420ebb46215/service/invoice.ts#L29

These (4 and 8 addresses) should probably be validated with regex rather than character length and have corresponding tests added.  Not sure if they have similar/same regext, but for example:  https://monero.stackexchange.com/questions/2554/what-is-the-regex-for-a-monero-address-or-payment-id

**Comment by RuiSiang** [comment]
Changed, thanks for the suggestion.
