### ISSUE TITLE
Not connecting to RPC Daemon

### ISSUE THREAD

**Issue by loasrtr** [RuiSiang/monero-merchant#93]
Hi, 
my monero-wallet-rcp and monerod daemon is running. i change the .env many times. I always get monero addresses with XXXXXXXXXXX.....

is there a way to generate addresses from monero-wallet-rpc?

{"id":"tJpdPTub4mGRFnX6","address":"4AXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}

Kind Regards

**Comment by RuiSiang** [comment]
I think you've accidentally set `CRYPTO_MOCK` to true

**Comment by sequoiadotdev** [comment]
> I think you've accidentally set `CRYPTO_MOCK` to true

nice opsec
